version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: "jwt_auth"
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - my-network

  go-app:
    build: "go-api/"
    container_name: "go-appQ"
    ports:
      - "4040:4040"
    depends_on:
      - "postgres"
    restart: always
    networks:
      - my-network

  frontend:
    build: "./"
    container_name: "react-app"
    ports:
      - "3030:3030"
    depends_on:
      - "go-app"
    restart: on-failure
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  postgres-data: 